# -*- coding: utf-8 -*-
"""NETS 213 Wikipedia Fun Facts Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvCNI0vqTABLGrjkCtFqw8TcB9awqxwb
"""

# !pip install wikipedia

import wikipedia
import pandas as pd

# Initialize lists to store titles and content
titles = []
contents = []

# Fetch 25 random Wikipedia pages
for _ in range(200):
    try:
        # Get a random Wikipedia page title
        random_page = wikipedia.random()
        content = wikipedia.page(
            random_page, auto_suggest=False
        ).content  # Disable auto_suggest

        # If DisambiguationError, pick the first suggestion
        # random_page = e.options[0]

        content = wikipedia.page(random_page).content

        # Store the title and first 500 characters of the content
        titles.append(random_page)
        contents.append(content[:500])
    except:
        # If the page doesn't exist, skip to the next iteration
        continue
# Create a DataFrame to store the data
df = pd.DataFrame({"Title": titles, "Content": contents})
df["Content"] = df["Content"].str.replace("\n", "", regex=False)
df["Content"] = df["Content"].str.replace("==", "", regex=False)

df.to_csv("/content/random_wikipedia_facts.csv", index=False)
df.head()

df["Content"].iloc[0]  # first fact

len(df)  # number of fun facts we have
