name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build frontend
        run: |
          cd src/frontend
          npm install
          npm run build --omit=dev

      - name: Copy frontend build to backend
        run: |
          rm -rf src/backend/frontend
          cp -r src/frontend/build src/backend/frontend

      - name: Display contents of src/backend
        run: |
          ls src/backend

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fun-facts"
          heroku_email: "liun0@seas.upenn.edu"
          appdir: "src/backend"
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
